import { CssVariableData } from "../../internalUtils/components/ComponentCssVariableTable";

export const cssVariablesData: CssVariableData[] = [
  {
    variable: "--border-base",
    description: "Base border width for button elements",
    defaultValue: "1px",
    rootValue: "1px",
  },
  {
    variable: "--radius-md",
    description: "Medium border radius for button corners",
    defaultValue: "4px",
    rootValue: "4px",
  },
  {
    variable: "--btn-padding",
    description: "Default padding for button elements",
    defaultValue: "8px 16px",
    rootValue: "8px 16px",
  },
  {
    variable: "--font-weight-semibold",
    description: "Font weight for button text",
    defaultValue: "600",
    rootValue: "600",
  },
  {
    variable: "--button-size",
    description: "Dynamic font size for button text (changes with size variants)",
    defaultValue: "var(--md-btn-size)",
    rootValue: "14px",
  },
  {
    variable: "--transition-duration-normal",
    description: "Normal transition duration for button interactions",
    defaultValue: "0.2s",
    rootValue: "0.2s",
  },
  {
    variable: "--transition-duration-fast",
    description: "Fast transition duration for active states",
    defaultValue: "0.1s",
    rootValue: "0.1s",
  },
  {
    variable: "--btn-right-margin",
    description: "Right margin for button spacing",
    defaultValue: "8px",
    rootValue: "8px",
  },
  {
    variable: "--sm-btn-size",
    description: "Font size for small button variant",
    defaultValue: "12px",
    rootValue: "12px",
  },
  {
    variable: "--md-btn-size",
    description: "Font size for medium button variant",
    defaultValue: "14px",
    rootValue: "14px",
  },
  {
    variable: "--lg-btn-size",
    description: "Font size for large button variant",
    defaultValue: "16px",
    rootValue: "16px",
  },
  {
    variable: "--btn-gap",
    description: "Gap between button text and icons",
    defaultValue: "8px",
    rootValue: "8px",
  },
  {
    variable: "--spacing-0",
    description: "Zero spacing value for positioning",
    defaultValue: "0",
    rootValue: "0",
  },
  {
    variable: "--shadow-sm",
    description: "Small shadow for button focus states",
    defaultValue: "0 1px 2px 0",
    rootValue: "0 1px 2px 0",
  },
  {
    variable: "--box-shadow-color",
    description: "Color for box shadows",
    defaultValue: "rgba(0, 0, 0, 0.1)",
    rootValue: "rgba(0, 0, 0, 0.1)",
  },
  {
    variable: "--btn-text-color",
    description: "Text color for text button variant",
    defaultValue: "var(--primary-color)",
    rootValue: "#007bff",
  },
  {
    variable: "--btn-text-background-color",
    description: "Background color for text button variant",
    defaultValue: "transparent",
    rootValue: "transparent",
  },
  {
    variable: "--btn-text-hover-color",
    description: "Text color for text button hover state",
    defaultValue: "var(--primary-hover-color)",
    rootValue: "#0056b3",
  },
  {
    variable: "--btn-text-hover-background-color",
    description: "Background color for text button hover state",
    defaultValue: "var(--primary-hover-bg-color)",
    rootValue: "rgba(0, 123, 255, 0.1)",
  },
  {
    variable: "--btn-outlined-color",
    description: "Border and text color for outlined button variant",
    defaultValue: "var(--primary-color)",
    rootValue: "#007bff",
  },
  {
    variable: "--btn-outlined-background-color",
    description: "Background color for outlined button variant",
    defaultValue: "transparent",
    rootValue: "transparent",
  },
  {
    variable: "--btn-full-background-color",
    description: "Background color for full button variant",
    defaultValue: "var(--primary-color)",
    rootValue: "#007bff",
  },
  {
    variable: "--btn-full-color",
    description: "Text color for full button variant",
    defaultValue: "white",
    rootValue: "white",
  },
  {
    variable: "--btn-full-hover-background-color",
    description: "Background color for full button hover state",
    defaultValue: "var(--primary-hover-color)",
    rootValue: "#0056b3",
  },
  {
    variable: "--btn-neon-color",
    description: "Primary color for neon button variant",
    defaultValue: "var(--neon-primary-color)",
    rootValue: "#00ff00",
  },
  {
    variable: "--btn-neon-background-color",
    description: "Background color for neon button variant",
    defaultValue: "transparent",
    rootValue: "transparent",
  },
  {
    variable: "--btn-neon-hover-background-color",
    description: "Background color for neon button hover state",
    defaultValue: "var(--neon-hover-color)",
    rootValue: "#00cc00",
  },
  {
    variable: "--btn-neon-hover-color",
    description: "Text color for neon button hover state",
    defaultValue: "white",
    rootValue: "white",
  },
];
